version: "3.1"

services:
  doc-converter:
    image: docker-hosted/doc-converter:latest
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - PORT=${PORT}
    restart: always
    expose:
      - "${PORT}"
    ports:
      - "${PORT}:8080"